name       : obconf
version    : 2.0.4
release    : 2
source     :
    - http://openbox.org/dist/obconf/obconf-2.0.4.tar.gz : 71a3e5f4ee246a27421ba85044f09d449f8de22680944ece9c471cd46a9356b9
license    : GPL-2.0-or-later
component  : desktop
summary    : Openbox configuration tool
description: |
    ObConf now easily installs new themes which use the .obt Openbox theme archive format for distribution. Just open any .obt theme archive in your file browser, or use the interface provided inside ObConf.
    You can also use ObConf to create .obt Openbox theme archives for distributing your own themes.
builddeps  :
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(libglade-2.0)
    - pkgconfig(libstartup-notification-1.0)
    - pkgconfig(obrender-3.5)
    - pkgconfig(obt-3.5)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
